name: liquibase-update
run-name: ${{ github.actor }} is learning GitHub Actions for liquibase updates
on:
  workflow_dispatch:  
  push:
    branches:
      - main
jobs:
  postgres:
    # Add "id-token" with the intended permissions.
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - name: 'Connect to cloud sql proxy'
      uses: mattes/gce-cloudsql-proxy-action@v1
      with:
        creds: ${{ secrets.CLOUD_SQL_PROXY }}
        instance: fast-api-230516:europe-west2:postgres-db-1

    - run: |
        wget -O- https://repo.liquibase.com/liquibase.asc | gpg --dearmor > liquibase-keyring.gpg && \
        cat liquibase-keyring.gpg | sudo tee /usr/share/keyrings/liquibase-keyring.gpg > /dev/null && \
        echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/liquibase-keyring.gpg] https://repo.liquibase.com stable main' | sudo tee /etc/apt/sources.list.d/liquibase.list

    - run: |
        sudo apt-get update
        sudo apt-get install --yes --no-install-recommends postgresql-client
        sudo apt-get install --yes --no-install-recommends liquibase

    - run: psql postgresql://postgres:kulgasimsim@127.0.0.1:5432/exampledb -c '\dt'

    - run: liquibase update --changelog-file=liquibase/changelog/exampledb_master.xml
#    - uses: liquibase-github-actions/update@v4.23.1
#      with:
#        changelogFile: "liquibase/changelog/exampledb_master.xml"
#        url: "jdbc:postgresql://127.0.0.1:5432/exampledb"
#        rollbackOnError: "true"
#        showSummary: "verbose"
#        username: "postgres"
#        password: "kulgasimsim"
