name: liquibase-update
run-name: ${{ github.actor }} is learning GitHub Actions for liquibase updates
on:
  workflow_dispatch:  
  push:
    branches:
      - main
jobs:
  postgres:
    # Add "id-token" with the intended permissions.
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

#    - id: 'auth'
#      uses: 'google-github-actions/auth@v1'
#      with:
#        workload_identity_provider: 'projects/81869977343/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
#        service_account: 'default-service-account@fast-api-230516.iam.gserviceaccount.com'
#
#    - name: 'Set up Cloud SDK'
#      uses: 'google-github-actions/setup-gcloud@v1'
#      with:
#        version: '>= 363.0.0'

    - name: 'Connect to cloud sql proxy'
      uses: mattes/gce-cloudsql-proxy-action@v1
      with:
        creds: ${{ secrets.CLOUD_SQL_PROXY }}
        instance: fast-api-230516:europe-west2:postgres-db-1

    - run: |
          apt-get update
          apt-get install --yes --no-install-recommends postgresql-client

    - run: |
          psql postgresql://postgres:kulgasimsim@127.0.0.1:5432/exampledb